repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: pretty-format-json
    args: [--autofix, --indent, '2']
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-toml
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.16
  hooks:
  - id: mdformat
    exclude: |
      (?x)^(
        LICENSE
      )$
    additional_dependencies: [mdformat-gfm, mdformat-frontmatter]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.12.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2', --line-width, '120']
